---
- name: check if repo exists
  stat:
    path: /etc/yum.repos.d/elasticsearch-{{ es_version[0] }}.x.repo
  register: es_repo

- name: add elasticsearch-{{ es_version[0] }}.x repo
  yum_repository:
    name: elasticsearch-{{ es_version[0] }}.x
    description: Elasticsearch repository for {{ es_version[0] }}.x packages
    baseurl: https://artifacts.elastic.co/packages/{{ es_version[0] }}.x/yum
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    gpgcheck: yes
  when: not es_repo.stat.exists

- name: install elastic-{{ es_version }}
  yum:
    name: elasticsearch-{{ es_version }}
    state: present

- name: enable elasticSearch
  service:
    name: elasticsearch
    enabled: yes
