---
- name: List of Installed Plugins
  shell:  /usr/share/elasticsearch/bin/elasticsearch-plugin list
  register: installed_es_plugins
  changed_when: installed_es_plugins is not defined

- name: Install ElasticSearch plugins
  shell: /usr/share/elasticsearch/bin/elasticsearch-plugin install \
        {{ item.plugin.plugin_name}} --batch
  with_items:
    - "{{ es_plugins }}"
  when: item.plugin.list_name not in installed_es_plugins.stdout

- name: X-Pack Log4j Settings
  template:
    src: xpack.log4j2.properties.j2
    dest: /etc/elasticsearch/x-pack/log4j2.properties
  with_items:
    - "{{ es_plugins }}"
  when: ("x-pack" in item.plugin.list_name)
  notify: restart elastic

- name: Place ElasticSearch Security
  template:
    src: "{{ item.src }}"
    dest: /etc/elasticsearch/x-pack/{{ item.dest }}
    force: yes
  with_items:
    - src: role_mapping.yml.j2
      dest: role_mapping.yml
    - src: roles.yml.j2
      dest: roles.yml
  when: ("x-pack" in installed_es_plugins.stdout)
