---
- name: daemon reload
  systemd: daemon_reload=yes

- name: restart elastic
  service:
    name: elasticsearch
    state: restarted
  when: es_allow_restart

- name: start elastic
  service:
    name: elasticsearch
    state: started
